name: restinio_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  dart_mappable: ^4.2.2
  firebase_auth: ^5.2.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  firebase_storage: ^12.3.0
  flutter_bloc: ^8.1.6
  cached_network_image_platform_interface: ^4.1.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  skeletonizer: ^1.4.2
  rxdart: ^0.28.0
  collection: ^1.18.0
  wolt_modal_sheet: ^0.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  go_router_builder: ^2.7.1
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
