// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkK0pRRirEiyCPSVJxV9hZAeGDia0fes',
    appId: '1:73363374617:web:cf0af327b2bbfb9ec8a088',
    messagingSenderId: '73363374617',
    projectId: 'restinio-app',
    authDomain: 'restinio-app.firebaseapp.com',
    storageBucket: 'restinio-app.appspot.com',
    measurementId: 'G-HGDCVF4HV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVZY8jfm9iqwIbSwfzqiWavly4ZbV4AM',
    appId: '1:73363374617:android:2a5dbe522f70ded1c8a088',
    messagingSenderId: '73363374617',
    projectId: 'restinio-app',
    storageBucket: 'restinio-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiV1pKl7CS03dmdrR6bsEJ_WgBzWIdx_s',
    appId: '1:73363374617:ios:df2d92aad908ec81c8a088',
    messagingSenderId: '73363374617',
    projectId: 'restinio-app',
    storageBucket: 'restinio-app.appspot.com',
    iosBundleId: 'com.msa.restinio.app.restinioApp',
  );
}
